name: check-all-sites

on:
  schedule:
    - cron: "30 * * * *"
  workflow_dispatch:

jobs:
  health_check_job:
    runs-on: ubuntu-latest
    name: run health-check.sh
    steps:
      - uses: actions/checkout@v2
      - name: Run Shell Script
        id: shell_script_run
        run: bash ./health-check.sh